/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#8300b4",
        "on-error": "#490006",
        "secondary-fixed-dim": "#eaaeff",
        "primary": "#8ff5ff",
        "surface-container": "#1a1919",
        "surface-bright": "#2c2c2c",
        "on-secondary": "#390050",
        "on-tertiary-container": "#00213e",
        "inverse-surface": "#fcf8f8",
        "on-surface-variant": "#adaaaa",
        "surface-container-highest": "#262626",
        "surface-dim": "#0e0e0e",
        "tertiary-dim": "#4aa2f9",
        "on-tertiary": "#002e52",
        "inverse-on-surface": "#565554",
        "error-dim": "#d7383b",
        "on-tertiary-fixed": "#001930",
        "tertiary": "#65afff",
        "outline": "#777575",
        "secondary-dim": "#b90afc",
        "tertiary-container": "#4aa2f9",
        "on-primary": "#005d63",
        "on-error-container": "#ffa8a3",
        "surface-container-high": "#201f1f",
        "outline-variant": "#494847",
        "secondary-fixed": "#f0c1ff",
        "tertiary-fixed-dim": "#51a7fe",
        "error": "#ff716c",
        "inverse-primary": "#006a71",
        "primary-fixed": "#00eefc",
        "surface-variant": "#262626",
        "on-primary-fixed": "#003f43",
        "on-background": "#ffffff",
        "secondary": "#d575ff",
        "on-primary-container": "#005359",
        "surface": "#0e0e0e",
        "error-container": "#9f0519",
        "on-primary-fixed-variant": "#005e64",
        "background": "#0e0e0e",
        "secondary-container": "#9800d0",
        "on-secondary-container": "#fff5fc",
        "surface-tint": "#8ff5ff",
        "on-tertiary-fixed-variant": "#003b68",
        "primary-dim": "#00deec",
        "primary-fixed-dim": "#00deec",
        "tertiary-fixed": "#72b5ff",
        "on-secondary-fixed": "#58007a",
        "primary-container": "#00eefc",
        "on-surface": "#ffffff",
        "surface-container-low": "#131313",
        "surface-container-lowest": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Space Grotesk", "Noto Sans KR", "sans-serif"],
        body: ["Manrope", "Noto Sans KR", "sans-serif"],
        label: ["Manrope", "Noto Sans KR", "sans-serif"]
      }
    },
  },
  plugins: [],
}
